name: 'Lint, Build and Test API'

on: [push, pull_request]

env:
  ENV: development
  PORT: 3000
  DATABASE_URL: postgres://postgres:password@localhost:5432/mydb
  JWT_SECRET: testsecret
  JWT_EXPIRES_IN: 24

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run test
